### PR TITLE
Add star count to projects and libraries

### PR DESCRIPTION
**Pull request by sanders41**
Relates to #13

This adds a star count badge to projects and libraries. If this isn't what you had in mind no worries, feel free to close it.

### CODE REVIEW

**Comment by Xuanwo** [comment]
Thanks a lot. I'm currently working in this direction. Maybe we can rebase this PR on that.

**Comment by sanders41** [comment]
@Xuanwo question for you. I was rebasing this and also refactored to try to match better with your latest updates. I wanted to test that the `README.md` renders correctly and there are no errors, but it seems that it isn't possible to run outside of GitHub any more?

`cargo run` gives me `GITHUB_TOKEN env variable is required: NotPresent`. Looking at the `render` function this expected, but I'm wondering if there is another way to test the rendering?

**Comment by prrao87** [comment]
One suggestion/comment I had was, does it makes sense to store all these as markdown tables rather than bullet points? I think a table would look more organized and easier on the eye.

**Comment by sanders41** [comment]
You mean something along the lines of this right?

| Repo                                                                       | Repo Information                                                                                          | Contribute                                                                                                                       | Description                                                                                                                                                                        |
| -------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [Apache DataFusion Comet](./projects/apache_datafusion_comet.md)           | [github-repo](https://github.com/apache/datafusion-comet) | [start-contribute](https://github.com/apache/datafusion-comet/contribute) | A high-performance accelerator for [Apache Spark](https://spark.apache.org/), built on top of the powerful [Apache DataFusion](https://github.com/apache/datafusion) query engine. |
| [Apache HoraeDB (incubating)](<./projects/apache_horaedb_(incubating).md>) | [github-repo](https://github.com/apache/horaedb)          | [start-contribute](https://github.com/apache/horaedb/contribute)          | A high-performance, distributed, cloud native time-series database.                                                                                                                |

**Comment by prrao87** [comment]
@sanders41 indeed, yes! I presume the Tera template that generates the markdown would have to be modified to instead generate the same values inside a table?

**Comment by sanders41** [comment]
@Xuanwo I commented out some lines for testing and _think_ I got things tested well enough. In the diff it looks like there were several spacing changes to the `README`, but I thought I just accepted all the incoming changes. I think it's OK because it will just be recreated on merge anyway? If everything else looks good and you want me to clean up the diff on that file I can figure out what happened.

@prrao87 yes the [README.tmpl](https://github.com/rewrite-bigdata-in-rust/RBIR/blob/main/templates/README.tmpl) file would just need to be updated for a table. It should be fairly easy PR if @Xuanwo likes the idea.

**Comment by prrao87** [comment]
Yes, the concern is the table grows large and unwieldy if we add things like GitHub stars and other things etc., so it might make sense to not go down that road too. Happy to wait till there's consensus and a working template before doing anything further.

**Comment by Xuanwo** [comment]
Hi, @sanders41, thank you so much for your work! 

I'm a bit hesitant about adding stars in the `README`. I feel it's better not to suggest that one project is better than others, especially since we have many projects in the same field.

How about moving the star icons to their own pages just for project information?

---

According to the table view, I noticed that many projects have long descriptions, causing the table to have many wraps, as I experienced before.

image

How do you feel?

**Comment by sanders41** [comment]
Sure I can do that. It looks like there is a star count in the data you are retrieving from github so I could either add it as a badge next to the project name at the top, or as another bullet in the project info. Which would you prefer?

**Comment by Xuanwo** [comment]
> another bullet in the project info

I perfer this way for now. Thanks!

**Comment by sanders41** [comment]
I made the update and I also figured out how to run things locally so I updated the markdown files. I think it was correct to do that?

**Comment by Xuanwo** [comment]
> I made the update and I also figured out how to run things locally so I updated the markdown files. I think it was correct to do that?

Perfect! The only thing left is reverting all changes to `**/*.md` to make our PRs easier to track.

**Comment by sanders41** [comment]
> Perfect! The only thing left is reverting all changes to **/*.md to make our PRs easier to track.

Done

**Review by Xuanwo — APPROVED** [review]
Thank you @sanders41 for the PR and @prrao87 for the review!

**Pull request merged**
